### ISSUE TITLE
Error in android 14 (api  level 34)

### ISSUE THREAD

**Issue by kuvandikov** [alashow/datmusic-android#30]
```
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
```

**Comment by alashow** [comment]
Fixed in https://github.com/alashow/datmusic-android/commit/2ed9673bf6ddf0dd6376b9f55ac80dcb93afc574
